on: [push, pull_request]
name: CI
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: gofmt
      run: 'test -z $(gofmt -s -l .)'
      shell: bash
    - name: golint
      run: |
        go get -u golang.org/x/lint/golint
        golint `go list ./... | grep -v /vendor/`
    - name: go vet
      run: go vet ./...
    - name: Run tests with the race detector
      run: go test -v -race ./...
    - name: Generate test coverage
      run: go test -covermode=count -coverprofile=coverage.out ./...
    - name: Upload test coverage to CodeCov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.out
