name: integration

on:
  schedule:
    - cron: "0 10 * * 6"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Mod verify
      run: go mod verify

    - name: Run all tests including integration tests
      run: |
        cd mal
        go test -v --access-token=${{ secrets.MAL_ACCESS_TOKEN }}