on: [push, pull_request]
name: tests

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.x]
        platform: [ubuntu-latest]
        include:
        # Upload coverage only on this combination.
        - go-version: 1.x
            platform: ubuntu-latest
            upload-coverage: true
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache go modules
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-

    - name: Mod verify
      run: go mod verify

    - name: Run gofmt
      if: runner.os != 'Windows'
      run: '[ -z $(gofmt -s -l .) ] || (gofmt -s -d . && exit 1)'

    - name: Run golint
      run: |
        go get -u golang.org/x/lint/golint
        golint `go list ./... | grep -v /vendor/`

    - name: Run go vet
      run: go vet ./...

    - name: Run go test
      run: go test -v -race -covermode=count -coverprofile=coverage.out ./...

    - name: Upload test coverage to Coveralls
      if: ${{ matrix.upload-coverage }}
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        GO111MODULE=off go get github.com/mattn/goveralls
        $(go env GOPATH)/bin/goveralls -coverprofile=coverage.out -service=github
