name: update-secret

on:
  workflow_dispatch:

  schedule:
    - cron: "0 9 * * 6"

jobs:
  run-ci-process:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'

    - name: Checkout code
      uses: actions/checkout@v2

    # create go executable which updates the refresh token and then uses the GitHub API to store the refreshed token in the repository secrets.
    #
    # or use something like this: https://stackoverflow.com/questions/72424607/update-a-github-repository-secret-from-a-github-action